# This workflow takes the Bicep files within the Bicep folder and zips them together.  Then pushes/uploads them to the Octopus Instance specified. 
# Within the repo's secrets are the information relating to the Octopus Instance URL, API key and Space. 

name: StorageBicepTemplate
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - Storage-Template

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az bicep build --file main.bicep --outfile ./main.json
